# Generated by Django 4.2.16 on 2024-11-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdchat', '0003_rename_autor_message_autor_autor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
